server:
  servlet:
    context-path: /escola/app

spring:
  datasource:
    driver-class-name: ${ESCOLA_DB_DRIVER:org.h2.Driver}
    url: ${ESCOLA_DB_URL:jdbc:h2:mem:escola-test}
    username: ${ESCOLA_DB_USERNAME:sa}
    password: ${ESCOLA_DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
      
      