INSERT INTO ESCOLA(NOME) VALUES('COLEGIO LUIS EDUARDO MAGALHÃES');
INSERT INTO TURMA(NOME,ESCOLA_ID) VALUES('5 SERIE A MATUTINO',1);
INSERT INTO TURMA(NOME,ESCOLA_ID) VALUES('5 SERIE B MATUTINO',1);
INSERT INTO TURMA(NOME,ESCOLA_ID) VALUES('5 SERIE C VESPERTINO',1);
INSERT INTO TURMA(NOME,ESCOLA_ID) VALUES('5 SERIE D VESPERTINO',1);
