INSERT INTO User(nome, email, senha) VALUES('Adm', 'adm@email.com', '$2a$10$sFKmbxbG4ryhwPNx/l3pgOJSt.fW1z6YcUnuE2X8APA/Z3NI/oSpq');

INSERT INTO ESCOLA(NOME) VALUES('COLEGIO LUIS EDUARDO MAGALHÃES');
INSERT INTO TURMA(NOME,ESCOLA_ID) VALUES('5 SERIE A MATUTINO',1);
INSERT INTO TURMA(NOME,ESCOLA_ID) VALUES('5 SERIE B MATUTINO',1);
INSERT INTO TURMA(NOME,ESCOLA_ID) VALUES('5 SERIE C VESPERTINO',1);
INSERT INTO TURMA(NOME,ESCOLA_ID) VALUES('5 SERIE D VESPERTINO',1);
INSERT INTO ALUNO(NOME) VALUES('RODRIGO BEKER');
INSERT INTO ALUNO(NOME) VALUES('VINICIUS REIS');
INSERT INTO ALUNO(NOME) VALUES('CARLOS RAFAEL');
